/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * Button — allineato a Figma Design System 2026.
     * Props: variant (intent), size (Component dimension), radiusStyle (Style Standard vs Full-radius).
     */
    interface NdsButton {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * Icon only = solo icona, usa stone/padding-horizontal-only-icon (Figma)
          * @default false
         */
        "iconOnly": boolean;
        /**
          * Style = Standard → radius md; Style = Full-radius → radius full (pill)
          * @default "standard"
         */
        "radiusStyle": "standard" | "full";
        /**
          * Component dimension (Variable mode): xs, sm, md, lg, xl
          * @default "md"
         */
        "size": "xs" | "sm" | "md" | "lg" | "xl";
        /**
          * @default "button"
         */
        "type": "button" | "submit";
        /**
          * Component intent (Variable mode): primary, secondary, ghost, accent, info, positive, negative, warning
          * @default "primary"
         */
        "variant": "primary" | "secondary" | "ghost" | "accent" | "info" | "positive" | "negative" | "warning";
    }
    /**
     * Icon — web component del design system Namirial.
     * Usa il set Lucide; il nome è in kebab-case (es. "arrow-right", "check").
     * Il registro delle icone è in icon-registry.ts e può essere esteso con uno script
     * che sincronizza i nomi dal manifest Figma (lucide-icons/*).
     */
    interface NdsIcon {
        /**
          * Nome icona in kebab-case (es. "arrow-right", "link-2").
          * @default ""
         */
        "name": string;
        /**
          * Lato dell’icona in pixel (default 24).
          * @default 24
         */
        "size": number;
    }
}
declare global {
    /**
     * Button — allineato a Figma Design System 2026.
     * Props: variant (intent), size (Component dimension), radiusStyle (Style Standard vs Full-radius).
     */
    interface HTMLNdsButtonElement extends Components.NdsButton, HTMLStencilElement {
    }
    var HTMLNdsButtonElement: {
        prototype: HTMLNdsButtonElement;
        new (): HTMLNdsButtonElement;
    };
    /**
     * Icon — web component del design system Namirial.
     * Usa il set Lucide; il nome è in kebab-case (es. "arrow-right", "check").
     * Il registro delle icone è in icon-registry.ts e può essere esteso con uno script
     * che sincronizza i nomi dal manifest Figma (lucide-icons/*).
     */
    interface HTMLNdsIconElement extends Components.NdsIcon, HTMLStencilElement {
    }
    var HTMLNdsIconElement: {
        prototype: HTMLNdsIconElement;
        new (): HTMLNdsIconElement;
    };
    interface HTMLElementTagNameMap {
        "nds-button": HTMLNdsButtonElement;
        "nds-icon": HTMLNdsIconElement;
    }
}
declare namespace LocalJSX {
    /**
     * Button — allineato a Figma Design System 2026.
     * Props: variant (intent), size (Component dimension), radiusStyle (Style Standard vs Full-radius).
     */
    interface NdsButton {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Icon only = solo icona, usa stone/padding-horizontal-only-icon (Figma)
          * @default false
         */
        "iconOnly"?: boolean;
        /**
          * Style = Standard → radius md; Style = Full-radius → radius full (pill)
          * @default "standard"
         */
        "radiusStyle"?: "standard" | "full";
        /**
          * Component dimension (Variable mode): xs, sm, md, lg, xl
          * @default "md"
         */
        "size"?: "xs" | "sm" | "md" | "lg" | "xl";
        /**
          * @default "button"
         */
        "type"?: "button" | "submit";
        /**
          * Component intent (Variable mode): primary, secondary, ghost, accent, info, positive, negative, warning
          * @default "primary"
         */
        "variant"?: "primary" | "secondary" | "ghost" | "accent" | "info" | "positive" | "negative" | "warning";
    }
    /**
     * Icon — web component del design system Namirial.
     * Usa il set Lucide; il nome è in kebab-case (es. "arrow-right", "check").
     * Il registro delle icone è in icon-registry.ts e può essere esteso con uno script
     * che sincronizza i nomi dal manifest Figma (lucide-icons/*).
     */
    interface NdsIcon {
        /**
          * Nome icona in kebab-case (es. "arrow-right", "link-2").
          * @default ""
         */
        "name"?: string;
        /**
          * Lato dell’icona in pixel (default 24).
          * @default 24
         */
        "size"?: number;
    }

    interface NdsButtonAttributes {
        "variant": "primary" | "secondary" | "ghost" | "accent" | "info" | "positive" | "negative" | "warning";
        "size": "xs" | "sm" | "md" | "lg" | "xl";
        "radiusStyle": "standard" | "full";
        "iconOnly": boolean;
        "disabled": boolean;
        "type": "button" | "submit";
    }
    interface NdsIconAttributes {
        "name": string;
        "size": number;
    }

    interface IntrinsicElements {
        "nds-button": Omit<NdsButton, keyof NdsButtonAttributes> & { [K in keyof NdsButton & keyof NdsButtonAttributes]?: NdsButton[K] } & { [K in keyof NdsButton & keyof NdsButtonAttributes as `attr:${K}`]?: NdsButtonAttributes[K] } & { [K in keyof NdsButton & keyof NdsButtonAttributes as `prop:${K}`]?: NdsButton[K] };
        "nds-icon": Omit<NdsIcon, keyof NdsIconAttributes> & { [K in keyof NdsIcon & keyof NdsIconAttributes]?: NdsIcon[K] } & { [K in keyof NdsIcon & keyof NdsIconAttributes as `attr:${K}`]?: NdsIconAttributes[K] } & { [K in keyof NdsIcon & keyof NdsIconAttributes as `prop:${K}`]?: NdsIcon[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Button — allineato a Figma Design System 2026.
             * Props: variant (intent), size (Component dimension), radiusStyle (Style Standard vs Full-radius).
             */
            "nds-button": LocalJSX.IntrinsicElements["nds-button"] & JSXBase.HTMLAttributes<HTMLNdsButtonElement>;
            /**
             * Icon — web component del design system Namirial.
             * Usa il set Lucide; il nome è in kebab-case (es. "arrow-right", "check").
             * Il registro delle icone è in icon-registry.ts e può essere esteso con uno script
             * che sincronizza i nomi dal manifest Figma (lucide-icons/*).
             */
            "nds-icon": LocalJSX.IntrinsicElements["nds-icon"] & JSXBase.HTMLAttributes<HTMLNdsIconElement>;
        }
    }
}
